on: push

jobs:
  build_documenti:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install latexmk -y
        run: sudo apt install latexmk
      
      - name: Builda
        run: |
          shopt -s globstar
          for d_path in ./**/d_*/; do (cd $d_path; latexmk -pdflatex=lualatex ./d_*.tex) done

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          path: "**/*.pdf"
