name: Release Compiled PDF 
on: push

jobs:

  build_lettera:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: prova a compilare
        run: cd assegnazione_appalti/d_lettera_presentazione
        run: latexmk

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          path: "**/*.pdf"

