on: push

jobs:
    build_documenti:
        runs-on: ubuntu-latest
        steps:
          - name: Set up Git repository
            uses: actions/checkout@v3

          - name: Compile tex
            run: |
                sudo apt-get install -y latexmk
                shopt -s globstar
                for d_path in ./**/d_*/; do (cd $d_path; latexmk;) done

          - name: Upload PDF file
            uses: actions/upload-artifact@v3
            with:
              path: "**/*.pdf"
