on: push

jobs:
  build_documenti:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        dir: ['**/d_*/'] 

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Compile tex
        uses: xu-cheng/latex-action@v2
        with:
          glob_root_file: true
          latexmk_use_lualatex: true
          working_directory: ${{ matrix.dir }}
          root_file: "d_*.tex"
          work_in_root_file_dir: true

      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          path: "**/*.pdf"

  test:
    runs-on: ubuntu-latest
    name: Test Collect Directory Names action
    steps:
      - name: Get directory names
        id: get-directory-names
        uses: actions/collect-directory-names-by-file-glob
        with:
          file-glob: '**/*.spec.ts'
          search-directory: '/cypress'
          unique: "true"

      - name: Use Directory Names
        run: echo "Directory Names are ${{ steps.get-directory-names.outputs.directory-names}}
